name: RoadCraft Editor Save Build

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: RoadCraft Editor Save V${{ env.VERSION }}
          draft: false
          prerelease: ${{ contains(env.VERSION, 'beta') || contains(env.VERSION, 'alpha') }}

  build-launcher:
    needs: create-release
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}   # garante credenciais para upload
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Get productName from package.json
        run: echo "PRODUCT_NAME=$(jq -r .productName package.json)" >> $GITHUB_ENV

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install
        shell: bash

      - name: Build (gera NSIS, portable, AppImage, DMG etc.)
        run: npm run build
        shell: bash

      # ───────────────────────────────────────────────────────────────────────
      # Debug #1: listar tudo em dist/ para confirmar nomes
      - name: Listar arquivos em dist/
        run: ls -R dist
        shell: bash

      # Debug #2: imprimir o upload_url gerado no create-release
      - name: Ver upload_url
        run: echo "UPLOAD_URL=${{ needs.create-release.outputs.upload_url }}"
        shell: bash

      # ───────────────────────────────────────────────────────────────────────
      # Upload dos artefatos gerados para o Release
      # ───────────────────────────────────────────────────────────────────────

      # --- Windows: NSIS installer + Portable ---
      - name: Upload Windows NSIS Installer x64
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: dist/${{ env.PRODUCT_NAME }}-windows-x64.exe
          asset_name: ${{ env.PRODUCT_NAME }}-windows-x64-installer.exe
          asset_content_type: application/octet-stream

      - name: Upload Windows NSIS Installer ia32
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: dist/${{ env.PRODUCT_NAME }}-windows-ia32.exe
          asset_name: ${{ env.PRODUCT_NAME }}-windows-ia32-installer.exe
          asset_content_type: application/octet-stream

      - name: Upload Windows Portable x64
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: dist/${{ env.PRODUCT_NAME }}-windows-x64-portable.exe
          asset_name: ${{ env.PRODUCT_NAME }}-windows-x64-portable.exe
          asset_content_type: application/octet-stream

      - name: Upload Windows Portable ia32
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: dist/${{ env.PRODUCT_NAME }}-windows-ia32-portable.exe
          asset_name: ${{ env.PRODUCT_NAME }}-windows-ia32-portable.exe
          asset_content_type: application/octet-stream

      # --- Linux (Ubuntu): AppImage + tar.gz ---
      - name: Upload Linux AppImage x64
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: dist/${{ env.PRODUCT_NAME }}-linux-x64.AppImage
          asset_name: ${{ env.PRODUCT_NAME }}-linux-x64.AppImage
          asset_content_type: application/octet-stream

      - name: Upload Linux tar.gz x64
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: dist/${{ env.PRODUCT_NAME }}-linux-x64.tar.gz
          asset_name: ${{ env.PRODUCT_NAME }}-linux-x64.tar.gz
          asset_content_type: application/gzip

      # --- macOS: DMG x64 e arm64 (usar “mac” em vez de “macos”) ---
      - name: Upload macOS DMG x64
        if: matrix.os == 'macos-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: dist/${{ env.PRODUCT_NAME }}-mac-x64.dmg
          asset_name: ${{ env.PRODUCT_NAME }}-mac-x64.dmg
          asset_content_type: application/x-apple-diskimage

      - name: Upload macOS DMG arm64
        if: matrix.os == 'macos-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: dist/${{ env.PRODUCT_NAME }}-mac-arm64.dmg
          asset_name: ${{ env.PRODUCT_NAME }}-mac-arm64.dmg
          asset_content_type: application/x-apple-diskimage
